# Generated by Django 4.2.6 on 2023-12-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_remove_meeting_end_time_remove_meeting_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='day',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
