# Generated by Django 4.2.6 on 2023-11-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_rename_office_position_remove_user_office_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
