# Generated by Django 4.2.6 on 2023-11-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_user_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(choices=[('Human Resources', 'Human Resources'), ('Marketing', 'Marketing'), ('Project Management', 'Project Management')], max_length=30),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(choices=[('Artificial Intelligence', 'Artificial Intelligence'), ('Cybersecurity', 'Cybersecurity'), ('Data Science', 'Data Science'), ('Web Development', 'Web Development')], max_length=30),
        ),
    ]
