# Generated by Django 4.2.6 on 2023-11-29 02:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_remove_event_group_remove_project_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_day',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='members_present',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='event_members_present', to=settings.AUTH_USER_MODEL),
        ),
    ]
