# Generated by Django 4.2.6 on 2023-11-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_alter_event_category_alter_event_end_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='meeting_day',
            field=models.CharField(choices=[('monday', 0), ('tuesday', 1), ('wednesday', 2), ('thursday', 3), ('friday', 4), ('saturday', 5), ('sunday', 6)], max_length=20),
        ),
        migrations.AlterField(
            model_name='availabilty',
            name='day',
            field=models.CharField(choices=[('monday', 0), ('tuesday', 1), ('wednesday', 2), ('thursday', 3), ('friday', 4), ('saturday', 5), ('sunday', 6)], max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='meeting_day',
            field=models.CharField(choices=[('monday', 0), ('tuesday', 1), ('wednesday', 2), ('thursday', 3), ('friday', 4), ('saturday', 5), ('sunday', 6)], max_length=20),
        ),
    ]
