# Generated by Django 4.2.5 on 2023-10-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_bids_date_last_bid_alter_comments_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bidders_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
