# Generated by Django 4.2.5 on 2023-10-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_bids_bidders_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(blank=True, default='images/no-image.png', upload_to='images/'),
        ),
    ]
